### ISSUE TITLE
Is this project kaput?

### ISSUE THREAD

**Issue by brandonparsons** [torquebox/stompbox#2]

**Comment by bbrowning** [comment]
Yes. It's not actively maintained, and there are no plans to update it. However, we'd welcome any community contributions and would be willing to let anyone from the community that desires to take over the project and continue to maintain it.

**Comment by brandonparsons** [comment]
Thanks for the clarification.  It seemed like a pretty cool idea, but I thought the 2-3 years of inactivity was a warning sign :)
